---
abstract: 'Class for using the functions, provided by the Microsoft Bing Translate API.'
author:
  - 'Meng-Jie Wang <taiwolf@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bing-Translate
requires:
  Data::Dumper: 0
  HTTP::Headers: 0
  HTTP::Request::Common: 0
  JSON: 0
  LWP::UserAgent: 0
  URI::Escape: 0
  strict: 0
  utf8: 0
  warnings: 0
version: 0.002
